config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :meetings
      get :participating_meetings
    end
  end
  
  resources :meetings, only: [:show, :new, :create, :destroy, :edit, :update]
  resources :participations, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true
  validates :place, presence: true
  validates :start_from, presence: true
  validates :content, presence: true
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: { case_sensitive: false }
  validates :profile, presence: true
  has_secure_password
  
  has_many :meetings
  has_many :participations
  has_many :participating_meetings, through: :participations, source: :meeting
  
  def hope(meeting)
    self.participations.find_or_create_by(meeting_id: meeting.id)
  end
  
  def unhope(meeting)
    participation = self.participations.find_by(meeting_id: meeting.id)
    participation.destroy if participation
  end
  
  def hope?(meeting)
    self.participating_meetings.include?(meeting)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit, :update]
  
  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    if logged_in?
      @meeting = current_user.meetings.build
    end
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)
    if @meeting.save
      flash[:success] = '交流会を登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '交流会の登録に失敗しました。'
      render 'new'
    end
  end

  def destroy
    @meeting.destroy
    flash[:success] = '交流会を削除しました。'
    redirect_back(fallback_location: root_path)
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    
    if @meeting.update(meeting_params)
      flash[:success] = '正常に更新されました'
      redirect_to @meeting
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end
  
  private
  
  def meeting_params
    params.require(:meeting).permit(:name, :place, :start_from, :content)
  end
  
  def correct_user
    @meeting = current_user.meetings.find_by(id: params[:id])
    unless @meeting
      redirect_to root_url
    end
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    meeting = Meeting.find(params[:meeting_id])
    current_user.hope(meeting)
    to_user = User.find(params[:user_id])
    ParticipationMailer.send_when_hope_email(to_user, current_user, meeting).deliver
    flash[:success] = '参加希望を出しました。'
    redirect_to root_path
  end

  def destroy
    meeting = Meeting.find(params[:meeting_id])
    current_user.unhope(meeting)
    to_user = User.find(params[:user_id])
    ParticipationMailer.send_when_unhope_email(to_user, current_user, meeting).deliver
    flash[:success] = '参加希望を取り消しました。'
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @meetings = Meeting.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :meetings, :participating_meetings]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザ登録しました。'
      redirect_to @user
    else
      flash[:danger] = 'ユーザ登録失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end
  
  def meetings
    @user = User.find(params[:id])
    @meetings = @user.meetings.order(id: :desc).page(params[:page])
  end
  
  def participating_meetings
    @user = User.find(params[:id])
    @participating_meetings = @user.participating_meetings.page(params[:page])
  end
    
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">BizChain</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '登録', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BizChain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_meetings.html.erb
<ul class="list-unstyled">
  <% meetings.each do |meeting| %>
    <li class="media mb-3">
      <div class="media-body">
        <div class="card">
          <p>開催者: <%= link_to meeting.user.name, user_path(meeting.user) %> </p>
          <p>交流会番号: <%= link_to meeting.id, meeting %></p>
          <p>交流会名: <%= meeting.name %></p>
          <p>開催場所: <%= meeting.place %></p>
          <p>開始日時: <%= meeting.start_from %></p>
          <div>
            <% if current_user == meeting.user %>
              <%= link_to '編集', edit_meeting_path(meeting), class: 'btn btn-sm btn-primary' %>
              <%= link_to "削除", meeting, method: :delete, data: { confirm: "本当によろしいですか？"}, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate meetings %>
</ul>

app/views/meetings/edit.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @meeting, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '交流会名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :place, '場所' %>
        <%= f.text_field :place, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :start_from, '開始日時' %>
        <%= f.datetime_select :start_from, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, '詳細' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>

      <%= f.submit '変更する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @meeting, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '交流会名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :place, '場所' %>
        <%= f.text_field :place, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :start_from, '開始日時' %>
        <%= f.datetime_select :start_from, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, '詳細' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>

      <%= f.submit '作成する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>交流会詳細</h1>
    <div>
      <p>開催者: <%= @meeting.user.name %> </p>
      <p>交流会名: <%= @meeting.name %> </p>
      <p>場所: <%= @meeting.place %> </p>
      <p>開始日時: <%= @meeting.start_from %> </p>
      <p>詳細: <%= safe_join(@meeting.content.split("\n"),tag(:br)) %> </p>
    </div>
    <div>
      <%= link_to '一覧に戻る', root_path %>
    </div>
    <div>
      <% unless current_user == @meeting.user %>
        <%= render 'participations/hope_button', meeting: @meeting %>
      <% end %>
    </div>
  </div>
</div>

app/views/participations/_hope_button.html.erb
<% if current_user.hope?(meeting) %>
    <%= form_with(model: current_user.participations.find_by(meeting_id: meeting.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :meeting_id, meeting.id %>
      <%= hidden_field_tag :user_id, meeting.user_id %>
      <%= f.submit '参加希望解除', class: 'btn btn-danger' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.participations.build, local: true) do |f| %>
      <%= hidden_field_tag :meeting_id, meeting.id %>
      <%= hidden_field_tag :user_id, meeting.user_id %>
      <%= f.submit '参加希望', class: 'btn btn-primary' %>
    <% end %>
  <% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <h1>交流会一覧</h1>
    <div class="col-sm-12">
      <%= render 'meetings/meetings', meetings: @meetings %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>BizChain</h1>
    <h2>異業種間交流会管理アプリ</h2>
    <%= link_to '登録はこちら', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div class="card">
            <p>ユーザ名: <%= user.name %></p>
            <p>プロフィール: <%= safe_join(user.profile.split("\n"),tag(:br)) %></p>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザ編集</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'E-mail' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile, 'プロフィール' %>
        <%= f.text_area :profile, class: 'form-control' %>
      </div>

      <%= f.submit '編集完了', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <h1>ユーザ一覧</h1>
  <div class="col-sm-12">
    <%= render 'users', users: @users %>
  </div>
</div>

app/views/users/meetings.html.erb
<div class="row card">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-4">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link">ユーザプロフィール</a></li>
      <li class="nav-item"><a href="<%= meetings_user_path(@user) %>" class="nav-link">開催交流会</a></li>
      <li class="nav-item"><a href="<%= participating_meetings_user_path(@user) %>" class="nav-link">参加交流会</a></li>
    </ul>
    <div>
      <% if current_user == @user %>
          <%= link_to '交流会登録', new_meeting_path, class: 'btn btn-lg btn-primary btn-block' %>
      <% end %>
    </div>
    <div>
      <%= render 'meetings/meetings', meetings: @meetings %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザ登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'E-mail' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Password(確認用)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'ユーザ登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/participating_meetings.html.erb
<div class="row card">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-4">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link">ユーザプロフィール</a></li>
      <li class="nav-item"><a href="<%= meetings_user_path(@user) %>" class="nav-link">開催交流会</a></li>
      <li class="nav-item"><a href="<%= participating_meetings_user_path(@user) %>" class="nav-link">参加交流会</a></li>
    </ul>
      <h2><%= @user.name %> さんが参加希望を出している交流会一覧</h2>
    <div>
      <%= render 'meetings/meetings', meetings: @participating_meetings %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row card">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-4">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link">ユーザプロフィール</a></li>
      <li class="nav-item"><a href="<%= meetings_user_path(@user) %>" class="nav-link">開催交流会</a></li>
      <li class="nav-item"><a href="<%= participating_meetings_user_path(@user) %>" class="nav-link">参加交流会</a></li>
    </ul>
    <div>
      <p>ユーザ名: <%= @user.name %> </p>
      <p>プロフィール: <%= safe_join(@user.profile.split("\n"),tag(:br)) %> </p>
      <p>
        <% if current_user == @user %>
          <%= link_to 'プロフィールを編集する', edit_user_path, class: 'btn btn-lg btn-primary' %>
        <% end %>
      </p>
    </div>
  </div>
</div>